ALTER TABLE incident ADD COLUMN mention_count INTEGER DEFAULT 1;

ALTER TABLE engineer ADD COLUMN team VARCHAR(255);
ALTER TABLE engineer ADD COLUMN status VARCHAR(64) DEFAULT 'available';
ALTER TABLE engineer ADD COLUMN p1_count INTEGER DEFAULT 0;
