CREATE TABLE watch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id VARCHAR(255),
    jira_issue_key VARCHAR(255),
    tagged_user VARCHAR(255),
    watch_start TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(64) DEFAULT 'waiting'
);

CREATE INDEX idx_watch_status ON watch (status);
CREATE INDEX idx_watch_expires_at ON watch (expires_at);
